### PR TITLE
Fix stack issue with ImmediateScheduler

### LINKED ISSUE #24: Segmentation Fault
The following code will cause php to seg fault:

```php
$observable = new Rx\Observable\ArrayObservable(range(1, 10000));
$observable->subscribe(new \Rx\Observer\CallbackObserver());
```
I'm guessing that this has something to do with the recursive actions in the `ImmediateScheduler` blowing the stack, because it works fine with the `VirtualTimeScheduler`.

### PR DESCRIPTION
**Pull request by mbonneau**
This fixes #24 .

### CODE REVIEW

File: lib/Rx/Scheduler/ImmediateScheduler.php [hunk 1]
```diff
@@ -26,41 +26,24 @@ public function scheduleRecursive($action)
...
-
-                        if ($isAdded) {
-                            $group->remove($d);
-                        } else {
-                            $isDone = true;
-                        }
+        $recursiveAction = function () use ($action, &$goAgain, $disposable) {
+            while ($goAgain) {
+                $goAgain = false;
+                $disposable->add($this->schedule(function () use ($action, &$goAgain, $disposable) {
```
Comment (davidwdan) [inline lib/Rx/Scheduler/ImmediateScheduler.php]: $disposable is not used in this closure

File: lib/Rx/Scheduler/ImmediateScheduler.php [hunk 2]
```diff
@@ -26,41 +26,24 @@ public function scheduleRecursive($action)
...
+                    return $action(function () use (&$goAgain, $action) {
```
Comment (davidwdan) [inline lib/Rx/Scheduler/ImmediateScheduler.php]: $action is not used in this closure
